title: <p align="center"> Emine Cerit </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/emine-cerit/">LinkedIn</a> |
  <a href="https://github.com/EmineCerit">GitHub</a>
  </p>
 
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
